# Generated by Django 4.2.6 on 2023-11-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_cartitem_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
