# Generated by Django 4.2.6 on 2023-11-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
    ]
