# Generated by Django 4.2.6 on 2023-11-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_cartitem_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['product__product_name']},
        ),
    ]
