# Generated by Django 4.2.6 on 2023-11-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',)},
        ),
    ]
