# Generated by Django 4.2.6 on 2023-11-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['product__product_name']},
        ),
    ]
